package dev.ny.aoc;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

//145250
public class Day6 {
    private static final Map<String, List<String>> LINKS = new HashMap<>();
    private static final Map<String, String> LINKS2 = new HashMap<>();
    private static int sum = 0;

    public static void main(String[] args) {
        INPUT.lines()
                .map(s -> s.split("\\)"))
                .forEach(e -> {
                    final List<String> list = LINKS.getOrDefault(e[0], new ArrayList<>());
                    list.add(e[1]);
                    LINKS.put(e[0], list);
                });
        INPUT.lines()
                .map(s -> s.split("\\)"))
                .forEach(e -> LINKS2.put(e[1], e[0]));
        findMinOrbit("YOU", "SAN");
        computeOrbits("COM", 0);
        System.out.println(sum);
    }

    private static void findMinOrbit(final String you, final String san) {
        List<String> first = allLinks(you);
        List<String> second = allLinks(san);
        List<String> uncommon = new ArrayList<>();
        uncommon.addAll(first.stream().filter(s -> !second.contains(s)).collect(Collectors.toList()));
        uncommon.addAll(second.stream().filter(s -> !first.contains(s)).collect(Collectors.toList()));
        System.out.println(uncommon.size() - 2);
    }

    private static List<String> allLinks(final String in) {
        List<String> l = new ArrayList<>();
        l.add(in);
        while (true) {
            final String s = LINKS2.get(l.get(l.size() - 1));
            if (s != null) {
                l.add(s);
            } else {
                break;
            }
        }
        return l;
    }

    private static void computeOrbits(final String name, final int directOrbits) {
        final List<String> list = LINKS.get(name);
        if (list != null) {
            list.forEach(e -> computeOrbits(e, directOrbits + 1));
        }
        sum += directOrbits;
    }


    private static final String INPUT = "HL2)HP5\n" +
            "PD5)SVL\n" +
            "GGS)YTS\n" +
            "59G)C67\n" +
            "V3R)BTY\n" +
            "B9B)4QH\n" +
            "P42)PNP\n" +
            "3MR)YPD\n" +
            "HPL)T7M\n" +
            "9T9)BV2\n" +
            "QTG)LZM\n" +
            "LYL)2K1\n" +
            "ZM2)CCK\n" +
            "983)QLL\n" +
            "WYK)SKS\n" +
            "G2H)5QT\n" +
            "GW2)39Q\n" +
            "K68)HBF\n" +
            "FLF)GYC\n" +
            "Y8H)B69\n" +
            "H61)TSN\n" +
            "J6L)PZH\n" +
            "BD3)WSD\n" +
            "321)HZ7\n" +
            "FC4)X58\n" +
            "7M7)SR7\n" +
            "KXX)S7P\n" +
            "JBT)HFR\n" +
            "DPQ)96V\n" +
            "47S)36P\n" +
            "JQ8)FJL\n" +
            "1PX)J2L\n" +
            "DR8)HJ5\n" +
            "1P6)GS4\n" +
            "LXJ)WDK\n" +
            "8BB)LYL\n" +
            "TPD)9XH\n" +
            "5ZB)TML\n" +
            "ZYQ)DLC\n" +
            "1D2)L82\n" +
            "SZX)TLH\n" +
            "3HG)2Z4\n" +
            "T16)DT9\n" +
            "TDS)8PD\n" +
            "Y9F)VNZ\n" +
            "7NW)LQD\n" +
            "F5W)88Z\n" +
            "YQH)N7L\n" +
            "TRH)V7C\n" +
            "FHB)WDL\n" +
            "DT3)BHQ\n" +
            "4Q8)MXM\n" +
            "J1X)5DP\n" +
            "172)6NG\n" +
            "SR7)FLL\n" +
            "DT9)PZP\n" +
            "M8V)FY6\n" +
            "RXG)Y4B\n" +
            "H5F)9G9\n" +
            "B53)F72\n" +
            "9JQ)2WM\n" +
            "422)BQD\n" +
            "96B)6XD\n" +
            "F89)LCS\n" +
            "F59)9H9\n" +
            "J73)JQ9\n" +
            "PNV)BC3\n" +
            "B84)N4Y\n" +
            "9FC)7L8\n" +
            "2ZK)79Z\n" +
            "7CM)6R3\n" +
            "2LL)N46\n" +
            "DXF)2RH\n" +
            "C6Q)JVW\n" +
            "96V)4FT\n" +
            "G86)3CT\n" +
            "Y4D)33X\n" +
            "MXM)BCN\n" +
            "KRR)S7L\n" +
            "BKX)8FF\n" +
            "RQ7)RLG\n" +
            "6Q5)93D\n" +
            "YCZ)J41\n" +
            "ZSM)QGQ\n" +
            "R72)2QY\n" +
            "848)SZX\n" +
            "93D)Z9Q\n" +
            "X5S)T2M\n" +
            "1H4)6Q5\n" +
            "3F1)M8L\n" +
            "Y4W)FLF\n" +
            "K7D)1DD\n" +
            "CGL)8VF\n" +
            "N46)LCX\n" +
            "WDL)XHZ\n" +
            "YZ4)SC1\n" +
            "6K8)D4Z\n" +
            "Z2B)F5J\n" +
            "SQF)1BV\n" +
            "NK2)BXT\n" +
            "SF7)H5Y\n" +
            "HBF)2GM\n" +
            "7RN)5N6\n" +
            "9XH)YGR\n" +
            "P7L)HWR\n" +
            "CRR)5JF\n" +
            "GGG)L41\n" +
            "3JH)HVX\n" +
            "BCH)LNN\n" +
            "4BG)XGX\n" +
            "JCZ)Q5T\n" +
            "SYH)H2H\n" +
            "CLB)TTD\n" +
            "1QW)MX8\n" +
            "F58)9C6\n" +
            "DZY)B84\n" +
            "D76)LX2\n" +
            "JDC)RKC\n" +
            "55J)B9B\n" +
            "DQY)1RB\n" +
            "41Q)VN9\n" +
            "TQW)CY7\n" +
            "G1F)SYH\n" +
            "9MQ)G1F\n" +
            "H1W)3LQ\n" +
            "Y5C)QBJ\n" +
            "CCK)PYL\n" +
            "C6D)P9Y\n" +
            "837)N5C\n" +
            "ZKQ)SPV\n" +
            "DT9)37T\n" +
            "FSQ)GQG\n" +
            "3GY)6BC\n" +
            "TP6)JWB\n" +
            "X42)9Y6\n" +
            "Z9Q)3G2\n" +
            "FF9)CFX\n" +
            "WJ8)873\n" +
            "TPP)VK6\n" +
            "5ZY)DT3\n" +
            "1LM)63J\n" +
            "21Z)SQF\n" +
            "RQT)VQT\n" +
            "CSP)H3T\n" +
            "3PC)S6B\n" +
            "337)D7H\n" +
            "HZ7)XRK\n" +
            "36P)8VL\n" +
            "R2C)LTF\n" +
            "NXN)5DQ\n" +
            "S24)5PL\n" +
            "X8H)7D5\n" +
            "LW1)GYR\n" +
            "H14)9SQ\n" +
            "P15)76B\n" +
            "31W)NX3\n" +
            "QTH)97M\n" +
            "35S)7XM\n" +
            "DK7)VGQ\n" +
            "VNZ)BGT\n" +
            "T6V)1MB\n" +
            "JK4)H92\n" +
            "BV1)ZPR\n" +
            "3YG)7WM\n" +
            "YNL)JQ8\n" +
            "H92)C6G\n" +
            "5GH)R7B\n" +
            "4SK)X7R\n" +
            "KYK)VTJ\n" +
            "DWX)13Z\n" +
            "2QN)XC3\n" +
            "MPF)CFJ\n" +
            "2DW)G9R\n" +
            "KGF)V15\n" +
            "BQD)W9L\n" +
            "CX6)LRG\n" +
            "TGZ)KC3\n" +
            "1S6)YCZ\n" +
            "S7L)3JH\n" +
            "K83)C6Q\n" +
            "H1X)K9L\n" +
            "ZPV)QYC\n" +
            "Z7D)CMZ\n" +
            "PVY)SNN\n" +
            "RVP)5B4\n" +
            "4SX)5J5\n" +
            "WK5)C4P\n" +
            "XZ3)8XF\n" +
            "T3J)337\n" +
            "X5D)DR8\n" +
            "S6B)9FC\n" +
            "4Z9)1F3\n" +
            "HF3)VCN\n" +
            "C37)2H4\n" +
            "71S)NYD\n" +
            "1MB)7CH\n" +
            "TXD)LYX\n" +
            "SF3)P7L\n" +
            "X4Z)VX8\n" +
            "XRL)RTX\n" +
            "F7V)QMZ\n" +
            "VR9)MHV\n" +
            "F6P)4FB\n" +
            "SC1)N9V\n" +
            "QSH)SG5\n" +
            "GVP)5DL\n" +
            "C4G)T1T\n" +
            "VH1)RH4\n" +
            "MZW)4W5\n" +
            "R7B)MRX\n" +
            "P4F)PY4\n" +
            "7YW)577\n" +
            "Y1Y)NGJ\n" +
            "642)M1Z\n" +
            "BLQ)Y4H\n" +
            "3DT)PRB\n" +
            "DPQ)K8G\n" +
            "JKL)N97\n" +
            "7KZ)ZY4\n" +
            "CX6)8RN\n" +
            "WM5)W5L\n" +
            "QBM)NK2\n" +
            "2Z4)X8H\n" +
            "T1T)5BV\n" +
            "2GM)5WD\n" +
            "LZM)V3R\n" +
            "S61)RN6\n" +
            "744)BD2\n" +
            "VQT)WBH\n" +
            "QVF)YGJ\n" +
            "P4B)XCQ\n" +
            "J41)3FX\n" +
            "NCP)BL5\n" +
            "1NK)VPM\n" +
            "9H9)47S\n" +
            "T92)5X8\n" +
            "W9W)439\n" +
            "ST9)HTJ\n" +
            "SMD)1NK\n" +
            "DGW)2QN\n" +
            "T7N)LDH\n" +
            "Y9B)3HG\n" +
            "BBW)3DP\n" +
            "QQS)1H3\n" +
            "YNM)P4F\n" +
            "J4X)KK5\n" +
            "XHS)FJP\n" +
            "L82)HVP\n" +
            "K9L)2RT\n" +
            "1VG)35S\n" +
            "7GK)RD6\n" +
            "1QV)BL4\n" +
            "5NM)Z91\n" +
            "FK8)DWX\n" +
            "JQ9)7TN\n" +
            "5J5)X7L\n" +
            "5X8)837\n" +
            "1DD)VYM\n" +
            "PKR)1QV\n" +
            "V32)Y5C\n" +
            "QMZ)XSF\n" +
            "CPY)8KQ\n" +
            "Y23)DQH\n" +
            "P9Y)YBY\n" +
            "DQH)QQS\n" +
            "S98)VB3\n" +
            "DGF)MS9\n" +
            "MTR)T5J\n" +
            "PZP)6CK\n" +
            "G6T)3G9\n" +
            "JYX)ZSM\n" +
            "9G9)J2Q\n" +
            "F2F)NF1\n" +
            "8X9)JGY\n" +
            "7N3)91G\n" +
            "CJX)PCK\n" +
            "3BR)FP2\n" +
            "HTQ)JF1\n" +
            "XW6)XXN\n" +
            "Y47)LZQ\n" +
            "ZZZ)Y23\n" +
            "VYM)TXW\n" +
            "9G6)27H\n" +
            "Q5T)YLK\n" +
            "BV2)C1N\n" +
            "GZ4)K83\n" +
            "QXJ)JYX\n" +
            "M8P)YSL\n" +
            "741)VSZ\n" +
            "QXP)BFG\n" +
            "X2H)TJ1\n" +
            "H2H)G1T\n" +
            "L41)NH6\n" +
            "QBJ)8BB\n" +
            "XN5)LTC\n" +
            "26R)W2M\n" +
            "2N6)YJD\n" +
            "3LN)XHS\n" +
            "LRG)V65\n" +
            "4W5)B8Y\n" +
            "HG6)QC9\n" +
            "Z3L)GFD\n" +
            "MLK)Y1Y\n" +
            "13Z)LCC\n" +
            "4QH)G2H\n" +
            "XSF)M8R\n" +
            "VH7)K7D\n" +
            "V8N)YBV\n" +
            "751)7CM\n" +
            "NW1)P5H\n" +
            "7FK)SHV\n" +
            "R6J)V32\n" +
            "TK7)H61\n" +
            "2WM)26R\n" +
            "8RN)5VS\n" +
            "BSF)5ZB\n" +
            "WW5)QXV\n" +
            "N42)2JB\n" +
            "FKG)V4R\n" +
            "Q5T)7GK\n" +
            "XBL)546\n" +
            "1TC)Z4Y\n" +
            "4F9)ZKZ\n" +
            "XRK)J4X\n" +
            "JZK)XN5\n" +
            "W23)GZB\n" +
            "V65)TQW\n" +
            "BF7)DXT\n" +
            "726)3F1\n" +
            "L84)M8P\n" +
            "PDX)9QY\n" +
            "7D4)QSN\n" +
            "439)SCX\n" +
            "WBL)X42\n" +
            "9NG)P36\n" +
            "R51)R17\n" +
            "Z9F)321\n" +
            "SSS)NSV\n" +
            "DQ4)P15\n" +
            "R2D)2J4\n" +
            "LDH)V8N\n" +
            "96V)8J9\n" +
            "J9C)JDC\n" +
            "YBD)RQ3\n" +
            "7FK)RSW\n" +
            "YJD)1X7\n" +
            "LYX)VSR\n" +
            "HWZ)1T5\n" +
            "W32)B53\n" +
            "CT7)FPL\n" +
            "YLH)HS7\n" +
            "C67)2F6\n" +
            "TGL)1D2\n" +
            "XH1)751\n" +
            "B95)TP6\n" +
            "918)97J\n" +
            "LC7)52P\n" +
            "4W5)Y9F\n" +
            "5DP)XRP\n" +
            "JF1)KXX\n" +
            "95P)8NP\n" +
            "SR8)HG8\n" +
            "5ZB)D9Q\n" +
            "NRG)F2Z\n" +
            "FMT)J6S\n" +
            "2RC)DGF\n" +
            "4GZ)BXH\n" +
            "4FB)LWM\n" +
            "2YN)69M\n" +
            "PCK)9VS\n" +
            "9W8)L84\n" +
            "SMH)JHR\n" +
            "B2X)WM5\n" +
            "96B)BL2\n" +
            "F7V)R3L\n" +
            "DR3)JBY\n" +
            "ZF8)WRJ\n" +
            "1RB)KTP\n" +
            "TWN)5QY\n" +
            "N7L)WLK\n" +
            "XM8)NRG\n" +
            "T84)6K8\n" +
            "FY6)XDY\n" +
            "6GC)B9W\n" +
            "HFR)JRG\n" +
            "6BC)SYX\n" +
            "MM1)53N\n" +
            "TDS)KPB\n" +
            "CSD)VJN\n" +
            "XDC)DK7\n" +
            "6GV)KRR\n" +
            "5JW)15B\n" +
            "VTJ)SMD\n" +
            "MMS)4Z9\n" +
            "7WM)L7Q\n" +
            "7XM)3PC\n" +
            "QGQ)2GB\n" +
            "WXR)G6T\n" +
            "MTP)65C\n" +
            "5RP)C4G\n" +
            "PP3)Y2M\n" +
            "9SV)27Y\n" +
            "1ZD)2ZK\n" +
            "D2B)7TC\n" +
            "5BV)9MQ\n" +
            "V15)844\n" +
            "CMZ)1VG\n" +
            "6SH)BKX\n" +
            "C41)366\n" +
            "3V4)DPQ\n" +
            "8BB)MZW\n" +
            "HXL)X88\n" +
            "2YN)JKL\n" +
            "YPD)9PN\n" +
            "SPV)YOU\n" +
            "64L)S24\n" +
            "VGK)ZF1\n" +
            "ZJN)3WG\n" +
            "CSP)T7N\n" +
            "7CH)MWB\n" +
            "3DP)YNN\n" +
            "37T)3V4\n" +
            "Z5N)J1Z\n" +
            "578)FPJ\n" +
            "QYC)YNL\n" +
            "52P)FXJ\n" +
            "844)3GY\n" +
            "PWJ)S98\n" +
            "RB9)M14\n" +
            "T84)F89\n" +
            "C58)TCC\n" +
            "YVT)XW6\n" +
            "P49)STW\n" +
            "ZPR)TPD\n" +
            "Y4W)QFY\n" +
            "BNJ)VGT\n" +
            "3FX)1TC\n" +
            "SP3)FNK\n" +
            "B4Y)PKR\n" +
            "WHY)TDS\n" +
            "VVL)Z5D\n" +
            "C99)GS9\n" +
            "3WQ)MST\n" +
            "33X)7D4\n" +
            "BLD)9JQ\n" +
            "MQN)QRP\n" +
            "M8R)ST9\n" +
            "5DL)1P6\n" +
            "5QY)D2V\n" +
            "X7R)LSR\n" +
            "BXT)MG4\n" +
            "6TQ)LVD\n" +
            "XZQ)2KZ\n" +
            "PKW)V3X\n" +
            "QXP)95S\n" +
            "RRY)WLQ\n" +
            "KK5)VH7\n" +
            "PCG)1RS\n" +
            "SYX)SKW\n" +
            "GS9)ZPV\n" +
            "JBT)62J\n" +
            "N42)PJF\n" +
            "5QT)JYF\n" +
            "QMQ)QRD\n" +
            "W1P)WJY\n" +
            "YD2)51R\n" +
            "XPL)4L3\n" +
            "RXS)ZF8\n" +
            "B8B)3ZN\n" +
            "JGY)R51\n" +
            "9QY)WXJ\n" +
            "SHY)Y9B\n" +
            "HG8)TKR\n" +
            "L7Q)SZG\n" +
            "NYM)9T9\n" +
            "ZY4)6SF\n" +
            "879)41Q\n" +
            "YBY)LBZ\n" +
            "RNN)J9C\n" +
            "LB6)XQG\n" +
            "48W)XPL\n" +
            "W5K)TYT\n" +
            "JHR)94L\n" +
            "2P8)QBM\n" +
            "ZW3)BF7\n" +
            "JBD)1GF\n" +
            "X4Z)9NG\n" +
            "HC7)PD5\n" +
            "7JK)GNY\n" +
            "HQB)31W\n" +
            "M8L)JK4\n" +
            "LBZ)7NP\n" +
            "FC4)932\n" +
            "KGF)WW6\n" +
            "6R3)Z2B\n" +
            "1MM)3F3\n" +
            "WXR)8BP\n" +
            "SM6)JSD\n" +
            "8WV)6C1\n" +
            "Z9M)S99\n" +
            "GZB)MTR\n" +
            "39Q)1VY\n" +
            "VR9)PBP\n" +
            "B6D)MLC\n" +
            "DJW)YTY\n" +
            "X7L)R6J\n" +
            "YNN)G86\n" +
            "ZPV)NYM\n" +
            "8KQ)5N5\n" +
            "K1Y)D8G\n" +
            "SVK)M3R\n" +
            "ZZD)XBJ\n" +
            "5VS)M8V\n" +
            "5N5)JZK\n" +
            "D2V)Y8H\n" +
            "SZG)FMS\n" +
            "CG2)2S3\n" +
            "2H4)9P8\n" +
            "9XY)SMV\n" +
            "1YJ)3DT\n" +
            "932)NDV\n" +
            "3PK)PKW\n" +
            "8PD)T4Z\n" +
            "6C1)578\n" +
            "6NK)2LL\n" +
            "NF1)H4Z\n" +
            "KC3)YQ2\n" +
            "1F3)B9V\n" +
            "XLH)H1W\n" +
            "1RS)YQH\n" +
            "R3L)92R\n" +
            "COM)K9X\n" +
            "TTD)BNJ\n" +
            "4SV)5HZ\n" +
            "549)J2W\n" +
            "S96)4JG\n" +
            "88Z)TK7\n" +
            "7D4)JPH\n" +
            "PYG)F76\n" +
            "TSC)W23\n" +
            "9Y6)48W\n" +
            "S7P)QMQ\n" +
            "15Y)NGF\n" +
            "82B)NL3\n" +
            "2RH)BW5\n" +
            "B8Y)MM1\n" +
            "L6M)JRV\n" +
            "53V)S61\n" +
            "K8G)7YW\n" +
            "N5S)VQ8\n" +
            "W2H)WK7\n" +
            "GS7)3ZK\n" +
            "WSD)965\n" +
            "J2W)7FK\n" +
            "PNS)S6T\n" +
            "XHS)9LF\n" +
            "1Z3)WJ4\n" +
            "7F3)8X9\n" +
            "XRP)1KP\n" +
            "QGR)QNM\n" +
            "5CB)N5N\n" +
            "T21)F2F\n" +
            "FP2)XZ9\n" +
            "7L8)BCH\n" +
            "B9W)KCL\n" +
            "XNB)JFV\n" +
            "H4Z)2V1\n" +
            "C1N)DXF\n" +
            "LTF)918\n" +
            "KMJ)WSW\n" +
            "CYN)Y7D\n" +
            "KG3)XNB\n" +
            "SGC)TXD\n" +
            "KPB)Q9J\n" +
            "Y4B)KNW\n" +
            "MBC)XY7\n" +
            "XY1)717\n" +
            "VTH)RXS\n" +
            "VK6)S96\n" +
            "HP5)T6H\n" +
            "BMC)15Y\n" +
            "X6L)D2B\n" +
            "S99)P6L\n" +
            "642)HWZ\n" +
            "Q9J)V3G\n" +
            "QM5)457\n" +
            "72F)TWN\n" +
            "YTS)K9N\n" +
            "VQ8)QXP\n" +
            "XN5)WMB\n" +
            "Z6B)1Z3\n" +
            "JFV)HZB\n" +
            "NH6)4BY\n" +
            "8VF)RQT\n" +
            "1F3)BP7\n" +
            "1LQ)WF3\n" +
            "RTX)SVK\n" +
            "RV4)572\n" +
            "61D)64D\n" +
            "SQY)XHJ\n" +
            "TFB)KMX\n" +
            "GD7)RRY\n" +
            "TJ1)FC4\n" +
            "J5K)PYG\n" +
            "WLK)DGW\n" +
            "PYL)F58\n" +
            "PY4)X61\n" +
            "K5P)W32\n" +
            "SMD)GSG\n" +
            "SY2)XLH\n" +
            "43L)XX5\n" +
            "4DJ)NVS\n" +
            "GF5)T8J\n" +
            "R6J)T16\n" +
            "6NG)W1R\n" +
            "LCS)6WZ\n" +
            "N9V)JBN\n" +
            "H9N)86Z\n" +
            "NS9)3MR\n" +
            "C2R)DLH\n" +
            "NM3)9H4\n" +
            "YSL)CQC\n" +
            "N8X)GZ4\n" +
            "XVG)Z9F\n" +
            "FPL)LXJ\n" +
            "PZH)ZJN\n" +
            "B9V)W2H\n" +
            "XDC)PNS\n" +
            "873)V82\n" +
            "Q6L)S21\n" +
            "P4R)642\n" +
            "YQ2)QMR\n" +
            "C66)JJ2\n" +
            "CFJ)FFQ\n" +
            "NDV)MDT\n" +
            "D44)5ZY\n" +
            "HND)B8B\n" +
            "P67)PCG\n" +
            "QC9)C58\n" +
            "6Z5)3PK\n" +
            "N5N)CPY\n" +
            "6NG)N8P\n" +
            "6ND)LC7\n" +
            "2RT)GBM\n" +
            "GWW)WJB\n" +
            "5DQ)3WS\n" +
            "5WD)1MM\n" +
            "SQY)1LM\n" +
            "STW)2HX\n" +
            "R2T)1S1\n" +
            "8BP)XMG\n" +
            "VPM)PVP\n" +
            "HWR)858\n" +
            "N8P)ZDH\n" +
            "3G2)4KC\n" +
            "T8J)5HL\n" +
            "VLG)WBL\n" +
            "ZKZ)QM5\n" +
            "4L3)5PN\n" +
            "G9R)WYK\n" +
            "SH1)K2B\n" +
            "JRG)9MN\n" +
            "WBH)B7R\n" +
            "4FT)Y72\n" +
            "LCX)VL5\n" +
            "1H4)1XQ\n" +
            "DLH)848\n" +
            "V3X)7F3\n" +
            "CT7)SF7\n" +
            "M6J)Q7R\n" +
            "5B4)YLH\n" +
            "SNN)XZQ\n" +
            "5GH)DV3\n" +
            "GS7)JCZ\n" +
            "D9Q)CJX\n" +
            "MX8)172\n" +
            "MG4)J73\n" +
            "RQ3)9G6\n" +
            "FJP)SC6\n" +
            "SKW)NDP\n" +
            "1YN)T21\n" +
            "1H3)GW2\n" +
            "YBD)6PV\n" +
            "62J)MLK\n" +
            "BFG)GGS\n" +
            "GYR)P49\n" +
            "6TQ)8Z3\n" +
            "JSD)87S\n" +
            "V82)53V\n" +
            "HTQ)YNM\n" +
            "CJM)FHB\n" +
            "JBD)SQY\n" +
            "XY7)MPF\n" +
            "RN6)Q4W\n" +
            "VN9)2MT\n" +
            "3VM)61H\n" +
            "RN2)QGR\n" +
            "BV6)BLQ\n" +
            "3WG)XPY\n" +
            "B69)TGL\n" +
            "3VT)HG6\n" +
            "BL2)M1P\n" +
            "1BV)2DW\n" +
            "75P)3WQ\n" +
            "9PN)CG2\n" +
            "DGF)J78\n" +
            "LQD)5GH\n" +
            "L2H)96B\n" +
            "XX5)82W\n" +
            "GYC)SGC\n" +
            "LYL)S9Z\n" +
            "HZB)D8R\n" +
            "K9N)6SH\n" +
            "6R3)S3N\n" +
            "NGJ)VB5\n" +
            "QLL)SH1\n" +
            "366)6Z5\n" +
            "QRP)9XY\n" +
            "NL3)21Z\n" +
            "2G7)MJZ\n" +
            "P6L)RN2\n" +
            "DSH)GBJ\n" +
            "VGQ)95P\n" +
            "N97)94D\n" +
            "BD2)X47\n" +
            "T6H)VMN\n" +
            "G1R)B6D\n" +
            "B7R)R72\n" +
            "K9X)1PX\n" +
            "NJ8)2RC\n" +
            "S9Z)ZM2\n" +
            "HW5)FMT\n" +
            "FPJ)M5C\n" +
            "MST)1P9\n" +
            "965)X32\n" +
            "NX3)CGK\n" +
            "717)DR3\n" +
            "1D2)TSC\n" +
            "RXH)H9N\n" +
            "8G2)HPL\n" +
            "D8G)XXT\n" +
            "5QT)4SX\n" +
            "1XS)NHG\n" +
            "M9V)PF2\n" +
            "4FB)744\n" +
            "8NP)5JW\n" +
            "LZM)H14\n" +
            "J9C)484\n" +
            "7TC)Z4B\n" +
            "Z27)1LQ\n" +
            "RKC)GVP\n" +
            "RQC)JBD\n" +
            "LVD)FKJ\n" +
            "GFD)HQB\n" +
            "8J9)1ZD\n" +
            "6SF)SAN\n" +
            "SC8)BK9\n" +
            "VGT)JX7\n" +
            "KCZ)4HT\n" +
            "K9L)MQN\n" +
            "9MY)LZ5\n" +
            "JLP)WVP\n" +
            "HFV)Z7D\n" +
            "J1Z)LB6\n" +
            "X61)T92\n" +
            "WW6)VTH\n" +
            "KNC)NL4\n" +
            "C4P)RSJ\n" +
            "QNM)TFB\n" +
            "N12)983\n" +
            "3JJ)QR5\n" +
            "LZ5)H84\n" +
            "KTP)7JK\n" +
            "3WB)Q6L\n" +
            "MS9)YW7\n" +
            "DXT)Y4W\n" +
            "3G9)LVC\n" +
            "2K1)1YJ\n" +
            "577)ZQT\n" +
            "7NP)Y47\n" +
            "PVP)ZW3\n" +
            "V3H)SSS\n" +
            "ZVM)ZZZ\n" +
            "1GF)ZYQ\n" +
            "HVX)R2D\n" +
            "J9G)4GZ\n" +
            "3FX)CX6\n" +
            "97J)X4Z\n" +
            "WMB)M2K\n" +
            "9LF)B95\n" +
            "QBJ)HF3\n" +
            "JWB)292\n" +
            "QRD)P42\n" +
            "Q4W)RV4\n" +
            "XPY)M5Y\n" +
            "5DQ)JGR\n" +
            "95S)GYM\n" +
            "T7M)SY2\n" +
            "6GV)PNV\n" +
            "P5H)7YV\n" +
            "6XD)FVC\n" +
            "ZRP)LWH\n" +
            "BP7)W78\n" +
            "6G4)741\n" +
            "G2B)HTQ\n" +
            "F2Z)D6P\n" +
            "XZ9)XVG\n" +
            "T7M)1H4\n" +
            "1X7)55J\n" +
            "94D)9ZH\n" +
            "HJ5)R2C\n" +
            "WSW)3VT\n" +
            "2JB)CLB\n" +
            "91G)GGG\n" +
            "S21)NJ8\n" +
            "1Z3)5RP\n" +
            "15B)WXR\n" +
            "Q63)PMD\n" +
            "18C)C2R\n" +
            "97M)DQ4\n" +
            "MRX)Y4D\n" +
            "82W)BBW\n" +
            "QR5)2P8\n" +
            "CYN)H5F\n" +
            "WRJ)PWK\n" +
            "XCQ)3V1\n" +
            "BFM)8LX\n" +
            "69M)HGF\n" +
            "LCC)9W8\n" +
            "15Y)71S\n" +
            "WLF)CRR\n" +
            "MDT)549\n" +
            "918)19W\n" +
            "J9B)82B\n" +
            "H6R)HL2\n" +
            "2S3)1XS\n" +
            "5JW)6ND\n" +
            "WF3)NCP\n" +
            "XGX)5CH\n" +
            "6WZ)SHY\n" +
            "J67)P4B\n" +
            "VSR)J6N\n" +
            "9ZH)35Y\n" +
            "MRJ)DSH\n" +
            "86Z)X2H\n" +
            "TXW)WJ8\n" +
            "3LQ)N8X\n" +
            "9H4)3LN\n" +
            "KK5)4SK\n" +
            "NHG)K4C\n" +
            "GYM)43L\n" +
            "XQ4)KDX\n" +
            "Z5D)DZY\n" +
            "H4Z)JBT\n" +
            "BK9)KYK\n" +
            "1KP)BV6\n" +
            "44Y)T6V\n" +
            "T1T)TRH\n" +
            "95Q)XZ3\n" +
            "47X)375\n" +
            "PRB)MJX\n" +
            "VL5)FR1\n" +
            "CGK)7RN\n" +
            "5CH)9BB\n" +
            "5WN)NVY\n" +
            "SKS)YVT\n" +
            "DV3)SM6\n" +
            "63J)ZRP\n" +
            "7YV)GY7\n" +
            "PKW)T3J\n" +
            "JRV)XQ4\n" +
            "2WM)XWK\n" +
            "F5J)GF5\n" +
            "5PL)5WN\n" +
            "LWH)J67\n" +
            "WJY)N39\n" +
            "N12)3WB\n" +
            "FLL)RB9\n" +
            "T5J)J9B\n" +
            "FFQ)YD2\n" +
            "R2D)SC8\n" +
            "VX8)6G4\n" +
            "VMN)PP3\n" +
            "NDP)V3H\n" +
            "V8N)2XQ\n" +
            "8VL)GD7\n" +
            "1S1)4F9\n" +
            "GHT)8G2\n" +
            "T8V)4T3\n" +
            "DLC)MBC\n" +
            "1RS)VH1\n" +
            "VN9)SMH\n" +
            "N39)RNN\n" +
            "W78)SCY\n" +
            "3F3)Z17\n" +
            "8LX)ZQY\n" +
            "3VT)B11\n" +
            "9BB)SP3\n" +
            "D8R)NW1\n" +
            "NGF)ZL8\n" +
            "NVS)G2B\n" +
            "ZQY)4FY\n" +
            "BHQ)C99\n" +
            "2KZ)HFV\n" +
            "D6P)NM3\n" +
            "YTY)4DJ\n" +
            "6PV)61D\n" +
            "TK7)1WL\n" +
            "1VG)F7V\n" +
            "5JF)75P\n" +
            "XWK)LZZ\n" +
            "V7C)NXN\n" +
            "RSJ)XY1\n" +
            "BCN)K5P\n" +
            "TCC)3YG\n" +
            "V4R)RHF\n" +
            "1P9)NHK\n" +
            "JJ2)CW6\n" +
            "SCY)CYN\n" +
            "Z17)ZZD\n" +
            "VMQ)BV1\n" +
            "XMG)44Y\n" +
            "H84)726\n" +
            "R72)KMJ\n" +
            "546)WK5\n" +
            "T4Z)QSH\n" +
            "CFX)WLF\n" +
            "JGR)TGZ\n" +
            "V7C)HXL\n" +
            "PBP)RB5\n" +
            "KMX)7M7\n" +
            "N65)MMS\n" +
            "XXN)9SV\n" +
            "VLN)422\n" +
            "RTX)8MY\n" +
            "J6S)TTH\n" +
            "YGJ)4SV\n" +
            "FN9)59G\n" +
            "NYD)H5N\n" +
            "YW7)8WV\n" +
            "GNY)7NW\n" +
            "TYT)YZ4\n" +
            "BL2)64L\n" +
            "HS7)P4R\n" +
            "XHJ)XDC\n" +
            "N5C)HND\n" +
            "CW6)W9W\n" +
            "8FF)3YH\n" +
            "HD3)Z6B\n" +
            "2J4)J9G\n" +
            "7G7)KM7\n" +
            "S6T)BLD\n" +
            "WDK)Q63\n" +
            "PJF)PH3\n" +
            "ZGX)DJW\n" +
            "JBY)HCG\n" +
            "SMV)M9V\n" +
            "3ZN)B2X\n" +
            "RB5)VMQ\n" +
            "XXT)YBD\n" +
            "35Y)5BH\n" +
            "ZF1)LW1\n" +
            "LTC)D44\n" +
            "SHV)C41\n" +
            "WJB)HD3\n" +
            "MHV)VLG\n" +
            "W5L)FSQ\n" +
            "FVC)QTH\n" +
            "QR5)FLP\n" +
            "8MY)C6D\n" +
            "KDX)J6L\n" +
            "ZQT)95Q\n" +
            "SH1)WHY\n" +
            "BL4)JLP\n" +
            "VB3)RQ7\n" +
            "GY7)ZGX\n" +
            "RH4)XNZ\n" +
            "D4Z)VFR\n" +
            "ZZZ)PDX\n" +
            "NM3)QTG\n" +
            "6CK)XRL\n" +
            "92R)XH1\n" +
            "LBZ)SR8\n" +
            "JNM)BTB\n" +
            "Q7R)FK8\n" +
            "M2K)JV2\n" +
            "457)1S6\n" +
            "Q6L)B4Y\n" +
            "BC3)2G7\n" +
            "VJN)6NK\n" +
            "B9W)CGL\n" +
            "WVP)BSF\n" +
            "HVP)VGK\n" +
            "9MN)879\n" +
            "YLK)QVF\n" +
            "J2Q)QXJ\n" +
            "MLC)47X\n" +
            "NHK)DQY\n" +
            "9G9)18C\n" +
            "2X2)Z9M\n" +
            "375)QGC\n" +
            "572)F59\n" +
            "YJD)RQC\n" +
            "X47)BFM\n" +
            "M14)N5S\n" +
            "S3N)6GC\n" +
            "4T3)C66\n" +
            "4DJ)X5D\n" +
            "P36)W5K\n" +
            "H5Y)SF3\n" +
            "WXJ)CT7\n" +
            "BL5)ZVM\n" +
            "JTW)6GV\n" +
            "M1Z)17T\n" +
            "27Y)ZKQ\n" +
            "1XQ)TTF\n" +
            "LZQ)DPY\n" +
            "Z9F)J1X\n" +
            "NL4)X6L\n" +
            "LCC)HMV\n" +
            "RD6)KCZ\n" +
            "M1P)H6R\n" +
            "TKR)3VM\n" +
            "1WL)CSD\n" +
            "KCL)RVP\n" +
            "QGC)HC9\n" +
            "V3G)Z5N\n" +
            "NSV)9MY\n" +
            "VFR)G1R\n" +
            "M5Y)VR9\n" +
            "S9Z)KNC\n" +
            "YQH)N12\n" +
            "K4C)T84\n" +
            "4JG)T8V\n" +
            "SG5)JNM\n" +
            "79Z)V5L\n" +
            "PWK)MRJ\n" +
            "95Q)J5K\n" +
            "FXJ)FN9\n" +
            "7D5)KGF\n" +
            "K2B)VD1\n" +
            "QSN)4Q8\n" +
            "PD7)SLF\n" +
            "BKX)WW5\n" +
            "YGR)PWJ\n" +
            "LWM)XBL\n" +
            "XDY)3JJ\n" +
            "9VS)D76\n" +
            "3WS)4BG\n" +
            "B11)F6P\n" +
            "94L)N42\n" +
            "VTH)PD7\n" +
            "9H9)N65\n" +
            "YNL)2N6\n" +
            "JV2)CJM\n" +
            "M5C)7G7\n" +
            "RH4)W1P\n" +
            "64D)BD3\n" +
            "FKJ)R2T\n" +
            "Z91)RXH\n" +
            "FJL)RXG\n" +
            "Y2M)DM4\n" +
            "2F6)L6M\n" +
            "27Q)KG3\n" +
            "9SQ)M6J\n" +
            "KMJ)Z27\n" +
            "3ZK)CDV\n" +
            "3YH)1YN\n" +
            "SCX)NS9\n" +
            "C6G)27Q\n" +
            "GQG)5CB\n" +
            "C6L)5C1\n" +
            "MJZ)NP1\n" +
            "BGT)C37\n" +
            "NXN)P67\n" +
            "ZL8)FKG\n" +
            "36P)JTW\n" +
            "LSR)X5S\n" +
            "2XQ)H1X\n" +
            "X58)L2H\n" +
            "G1T)HC7\n" +
            "FLF)Z3L\n" +
            "XX5)7KZ\n" +
            "SLF)VVL\n" +
            "ZDH)TTQ\n" +
            "WK7)F5W\n" +
            "8XF)K1Y\n" +
            "87S)3BR\n" +
            "W2M)GHT\n" +
            "PF2)2YN\n" +
            "17T)HW5\n" +
            "TSN)2X2\n" +
            "Z4Y)BWY\n" +
            "J2L)PVY\n" +
            "76B)K68\n" +
            "H5F)XM8\n" +
            "TTQ)GWW\n" +
            "61H)MTP\n" +
            "JYF)C6L\n" +
            "MBC)BMC\n" +
            "PMD)TPP\n" +
            "MJX)CSP\n" +
            "LZ5)1QW\n" +
            "XBJ)FF9\n" +
            "T2M)6TQ\n" +
            "53N)GS7\n" +
            "2QY)VLN\n" +
            "RLG)72F\n" +
            "HC9)5NM\n" +
            "YBV)7N3";

}
